various

diff --git a/.local/bin/statusbar/dwm-status b/.local/bin/statusbar/dwm-status
--- a/.local/bin/statusbar/dwm-status
+++ b/.local/bin/statusbar/dwm-status
@@ -9,13 +9,14 @@
 # the dwm patch status2d is used to add color
 # process needs to be disconnected from dwm for restart to work
 
-#############
-### SETUP ###
-#############
+### SETUP:
 
 # checking if script is already running
 for pid in "$(pidof -x $(basename $0))"; do
-   [[ $pid != $$ ]] && exit 1
+    if [[ $pid != $$ ]]; then
+        echo 'ERROR: script is already running'
+        exit 1
+    fi
 done
 
 # cleaning up processes when killed
@@ -29,18 +30,16 @@ pipe="$STATUS_PIPE"
 [[ -e $pipe ]] && rm "$pipe"
 mkfifo "$pipe"
 
-# separator symbols
-sep="^c$BLUE^|^d^"
+# separator symbol
+sep="^c$BLACK_BRIGHT^|^d^"
 
-#################
-### FUNCTIONS ###
-#################
+### FUNCTIONS:
 
 # updating modules on specified interval
 loop() {
     while true; do
         "$1"
-        sleep "$2" 
+        sleep "$2"
     done > "$pipe" &
 }
 
@@ -67,9 +66,7 @@ assemble() {
     done
 }
 
-###############
-### RUNNING ###
-###############
+### RUNNING:
 
 "sb-volume" > "$pipe" &
 "sb-backlight" > "$pipe" &
